
# We establish a list of directories (=mounted disks) in the bricks directory
- find: paths={{ brick_directory }} file_type=directory
  register: found_paths

- set_fact: brick_dirs="{{ found_paths.files | map(attribute='path') | list }}"

- set_fact: bricks="{% set sep = joiner(",") %}{% for rep_d in rep_set %}{% for rep, rep_list in rep_d.iteritems() %}{% for host_d in rep_list %}{% for host, brick_list in host_d.iteritems() %}{% for brick in brick_list %}{{ sep() }}{{ rep }}:{{ brick_directory }}/{{ brick }}/volume:{{ host }}{% endfor %}{% endfor %}{% endfor %}{% endfor %}{% endfor %}"
  run_once: true
  tags: debug

# We need a list of hosts excluding the current host to initiate peer probing
- set_fact: comma_seperated_group_members={{ groups.all |join(',') }}


- file: path={{ item}}/volume state=directory
  with_items: "{{ brick_dirs }}"

- name: create gluster volume
  gluster_volume: state=present replicas=2 name=test1 bricks={{ item }} cluster=art-storage1-virt.maas,art-storage2-virt.maas,art-storage3-virt.maas,art-storage4-virt.maas
#  gluster_volume: state=present replicas=2 name=test1 bricks={{ item }} cluster={{ comma_seperated_group_members }}
  run_once: true
  with_items: "{{ bricks }}"

- name: start volume
  gluster_volume: name=test1 state=started