
# We establish a list of mounts, where each mount becomes a brick

- set_fact: brick_dirs="{{ ansible_mounts | map(attribute='mount') | list | difference( root ) }}"

# We need a list of hosts initiate peer probing

- set_fact: comma_seperated_group_members={{ groups[volume_group] |join(',') }}
  run_once: true

- file: path={{ item}}/volume0 state=directory
  with_items: "{{ brick_dirs }}"

- command: gluster peer probe {{ item }}
  with_items: "{{ groups[volume_group] | difference( [ ansible_fqdn ] ) }}"
  run_once: true
  ignore_errors: true

- name: create gluster volume
  gluster_volume: state=present replicas={{ replica_count}} name=test1 replicates={{ rep_set }} cluster={{ comma_seperated_group_members }}
  run_once: true

- name: start volume
  gluster_volume: name=test1 state=started
  run_once: true