# Format disks, force=no will not overwrite a device that already contains a filesystem
- name: Format disks
  filesystem: fstype={{ fs_type }} dev={{ item }} force=no
  with_items: "{{ storage_block_devices }}"

# Mount up device
- mount: name="{{ brick_directory }}/{{ item | basename }}" src={{ item }} fstype={{ fs_type }} state=mounted
  with_items: "{{ storage_block_devices }}"

